spring:
    application:
        name: authentication
    security:
        jwt:
            secret: xxdWXHtgXeXs0vaLSRjrORGDZvuRSoRHEOc43IyiLl6YOOjTW5U11Ae0fRA0vyeAHqOvepKwiHTkB/dLZP+ESw==
            expiration: 43200000
    jpa:
        open-in-view: false
server:
    port: 80
user:
    url:
        service: http://localhost:81/api/user